### ISSUE TITLE
Help I have a issues during the install bigsur process

### ISSUE THREAD

**Issue by DangTieuQuy** [ahianf/dell-vostro-3468-hackintosh#1]
When my laptop restart ( first time ) it self during the install bigsur process, it just boot again into MasOS eternal 
After that i manual switch the boot option into MacOS installer to continue the installing process but my laptop just show out black screen and restart immediately (I tried again many times but the results are still the same)
I'm new to hackintosh
I am using dell-vostro-3468 and I have not edited any files from your EFI (maybe this is the cause)
I want to install the latest version of BigSur and the wifi card I am using is code BCM94322HM8L
Please let me know what I have to do to correct the above error
Thank you and have a nice day

**Comment by ahianf** [comment]
Make a new efi without the kexts for Broadcom support, completely format your hard drive, also physically remove the Broadcom card from your computer (this is really important) and install Big Sur. Following this you should be fine

Also if you are new in hackintoshing, read the dortania guide and learn. It’s a long road but you can do it.

Remember to generate a new serial number, it’s necessary

Cheers
Ahian Fernández Puelles


Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Đàng Tiểu Quý ***@***.***>
Enviado: Saturday, April 24, 2021 3:45:51 PM
Para: ahianf/dell-vostro-3468-hackintosh ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [ahianf/dell-vostro-3468-hackintosh] Help I have a issues during the install bigsur process (#1)


When my laptop restart ( first time ) it self during the install bigsur process, it just boot again into MasOS eternal
After that i manual switch the boot option into MacOS installer to continue the installing process but my laptop just show out black screen and restart immediately (I tried again many times but the results are still the same)
I'm new to hackintosh
I am using dell-vostro-3468 and I have not edited any files from your EFI (maybe this is the cause)
I want to install the latest version of BigSur and the wifi card I am using is code BCM94322HM8L
Please let me know what I have to do to correct the above error
Thank you and have a nice day
