### ISSUE TITLE
Sleep Issue ?

### ISSUE THREAD

**Issue by m7mdcc** [ahianf/dell-vostro-3468-hackintosh#2]
Did you found any solution for sleep issue ? 

From my side it's doesn't come back from sleep ever :(

Used Same EFI folder , no change .. 
I disable sleep for now :(

**Comment by ahianf** [comment]
Sleep is hit or miss for me. My computer always wakes from sleep (using Big Sur) but sometimes the keyboard and touchpad dies.

Do you have your USB mapped? I provide kextinjectall but you MUST map your usb. Sleep issues can be caused by badly mapped USB ports.

Also, follow dortania guide for fixing sleep issues.

Cheers
Ahian Fernández Puelles

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: MOHAMMED MANSOUR ***@***.***>
Enviado: Wednesday, May 12, 2021 3:19:20 PM
Para: ahianf/dell-vostro-3468-hackintosh ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [ahianf/dell-vostro-3468-hackintosh] Sleep Issue ? (#2)


Did you found any solution for sleep issue ?

From my side it's doesn't come back from sleep ever :(

**Comment by m7mdcc** [comment]
> Do you have your USB mapped?

All of my USB Ports is working good . Do i need to do something else ? Can you guide me ? 

Thanks

I will follow this : https://www.olarila.com/topic/14220-video-guide-usb-port-mapping-guide-2021-bigsur-113-with-no-xhci-port-limit/

**Comment by ahianf** [comment]
If your USB are working just with my repo, that means you don’t have your usb ports mapped.

https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html

Dortania guide will help you more than I could, so please read every page carefully to understand what’s going on in my EFI folder


Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: MOHAMMED MANSOUR ***@***.***>
Enviado: Wednesday, May 12, 2021 6:10:47 PM
Para: ahianf/dell-vostro-3468-hackintosh ***@***.***>
Cc: ahianf ***@***.***>; Comment ***@***.***>
Asunto: Re: [ahianf/dell-vostro-3468-hackintosh] Sleep Issue ? (#2)


Do you have your USB mapped?

All of my USB Ports is working good . Do i need to do something else ? Can you guide me ?

Thanks

**Comment by m7mdcc** [comment]
Hmmm , i mapped USB Ports.. Sleep issue not solve . 

I'm not expert in opencore etc , but i found this repo https://github.com/visheshraghuvanshi/vostro3568
He doesn't include DW1506 Kext , even not all usb ports is enabled . but sleep work good more than expected . 

but i noticed its vostro 3568 , yours 3468 but both boot with me .. 

Could you please explain why its work good on that repo ? 

Thanks

**Comment by ahianf** [comment]
What wireless card do you have?

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: MOHAMMED MANSOUR ***@***.***>
Enviado: Thursday, May 13, 2021 1:37:29 AM
Para: ahianf/dell-vostro-3468-hackintosh ***@***.***>
Cc: ahianf ***@***.***>; Comment ***@***.***>
Asunto: Re: [ahianf/dell-vostro-3468-hackintosh] Sleep Issue ? (#2)


Hmmm , i mapped USB Ports.. Sleep issue not solve .

I'm not expert in opencore etc , but i found this repo https://github.com/visheshraghuvanshi/vostro3568
He doesn't include DW1506 Kext , even not all usb ports is enabled . but sleep work good more than expected .

but i noticed its vostro 3568 , yours 3468 but both boot with me ..

Could you please explain why its work good on that repo ?

Thanks

**Comment by m7mdcc** [comment]
I have this BCM4352

**Comment by ahianf** [comment]
If my repo is not working, try removing kexts one at the time.

Fires remove all the bcm related kexts, then work all the way up

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: MOHAMMED MANSOUR ***@***.***>
Enviado: Thursday, May 13, 2021 6:07:39 PM
Para: ahianf/dell-vostro-3468-hackintosh ***@***.***>
Cc: ahianf ***@***.***>; Comment ***@***.***>
Asunto: Re: [ahianf/dell-vostro-3468-hackintosh] Sleep Issue ? (#2)


I have this BCM4352

**Comment by m7mdcc** [comment]
Back with Good Result ! 

First , I disabled BCM Kexts . Same issue . then i try something really i don't know what its mean! 

Just copy some snippets from PCI Part from mentioned repo , to be like this : 
```
<key>DeviceProperties</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,GfxYTile</key>
				<data>AQAAAA==</data>
				<key>AAPL,ig-platform-id</key>
				<data>AADAhw==</data>
				<key>AAPL,slot-name</key>
				<string>Internal@0,2,0</string>
				<key>device-id</key>
				<data>FlkAAA==</data>
				<key>device_type</key>
				<string>VGA compatible controller</string>
				<key>disable-external-gpu</key>
				<data>AQAAAA==</data>
				<key>enable-hdmi20</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con2-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con2-type</key>
				<data>AAgAAA==</data>
				<key>framebuffer-fbmem</key>
				<data>AACQAA==</data>
				<key>framebuffer-patch-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-stolenmem</key>
				<data>AAAwAQ==</data>
				<key>framebuffer-unifiedmem</key>
				<data>AAAAgA==</data>
				<key>model</key>
				<string>Intel UHD Graphics 620</string>
			</dict>
			<key>PciRoot(0x0)/Pci(0x1F,0x3)</key>
			<dict>
				<key>layout-id</key>
				<integer>11</integer>
			</dict>
		</dict>
		<key>Delete</key>
		<dict/>
	</dict>
```

My thought tell me the issue is with GPU since its wake from sleep with black screen , sound working .. 

After editing PCI Part its work as expected !
