### ISSUE TITLE
Realtek SD Card Reader support

### ISSUE THREAD

**Issue by cr3ativec0mmons** [ahianf/dell-vostro-3468-hackintosh#5]
Hi, i wanted to ask if you have tried this kext that enables the sd card reader?

Heres the link: [https://github.com/0xFireWolf/RealtekCardReader](url)

**Comment by ahianf** [comment]
Nt tried, I'll let you know if works.

**Comment by cr3ativec0mmons** [comment]
I have other question. Apart from the camera, the microphone works good?

**Comment by ahianf** [comment]
Yes it works fine. Some features are Windows-only though, like noise reduction. But I prefer the noise reduction be done per app.

**Comment by cr3ativec0mmons** [comment]
Thanks for responding, i will consider installing Mac os in vacations
